// Code generated by goctl. DO NOT EDIT.
package types

type Rest struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Date struct {
	CreatedAt   int64  `json:"createAt,optional"`
	CreatedTime string `json:"createdTime,optional"`
	UpdatedAt   int64  `json:"updatedAt,optional"`
	UpdatedTime string `json:"updatedTime,optional"`
}

type Paginate struct {
	Current  int64 `form:"current,optional,default=1" json:"current,optional"`
	PageSize int64 `form:"pageSize,optional,default=10" json:"pageSize,optional"`
	Total    int64 `json:"total,optional"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type TokenData struct {
	AccessToken  string `json:"access_token"`
	ExpiresAt    int64  `json:"expires_at"`
	RefreshToken string `json:"refresh_token"`
	ReExpiresAt  int64  `json:"re_expires_at"`
}

type LoginResp struct {
	Rest
	Data TokenData `json:"data"`
}

type HelloData struct {
	Id int64 `json:"id"`
}

type HelloResp struct {
	Rest
	Data HelloData `json:"data"`
}

type ShowRoleReq struct {
	Id int64 `path:"id,optional"`
}

type RoleReq struct {
	Id          int64    `path:"id,optional"`
	ParentId    int64    `json:"parentId,optional"`
	Name        string   `json:"name"`
	Description string   `json:"description,optional"`
	MenuIds     []*int64 `json:"menuIds,optional"`
	Sort        int64    `json:"sort,optional"`
	Status      int64    `json:"status,optional"`
	Paginate
}

type Role struct {
	Id          int64    `json:"id"`
	ParentId    int64    `json:"parentId"`
	Name        string   `json:"name"`
	Description string   `json:"description,omitempty"`
	MenuIds     []*int64 `json:"menuIds,omitempty"`
	Level       string   `json:"level"`
	Sort        int64    `json:"sort"`
	Status      int64    `json:"status"`
	Date
	Children []*Role `json:"children,omitempty"`
}

type RoleResp struct {
	Rest
	Data Role `json:"data"`
}

type PaginateRole struct {
	Paginate
	Data []Role `json:"data"`
}

type IndexRoleResp struct {
	Rest
	Data PaginateRole `json:"data"`
}

type AllRoleResp struct {
	Rest
	Data []*Role `json:"data"`
}

type DataScopeReq struct {
	Id            int64    `path:"id"`
	DataScope     int64    `json:"dataScope"`
	DepartmentIds []*int64 `json:"departmentIds,optional"`
}

type DataScope struct {
	Id            int64    `path:"id"`
	DataScope     int64    `json:"dataScope"`
	DepartmentIds []*int64 `json:"departmentIds,omitempty"`
	RoleName      string   `json:"roleName"`
}

type DataScopeResp struct {
	Rest
	Data DataScope `json:"data"`
}

type MenuReq struct {
	MenuId    int64  `path:"menuId,optional"`    // path参数：菜单ID，作为可选项
	MenuName  string `json:"menuName,optional"`  // 模糊查询菜单名称，必传字段
	ParentId  int64  `json:"parentId,optional"`  // 查询指定父级菜单的子菜单，可选字段
	Status    int64  `json:"status,optional"`    // 菜单状态：启用或禁用，可选字段
	Visible   int64  `json:"visible,optional"`   // 菜单是否可见：0 - 不可见，1 - 可见，可选字段
	Order     int64  `json:"order,optional"`     // 排序顺序，可选字段
	Path      string `json:"path,optional"`      // 菜单路径，可选字段
	Component string `json:"component,optional"` // 菜单组件，可选字段
	Query     string `json:"query,optional"`     // 菜单查询，可选字段
	IsFrame   int64  `json:"isFrame,optional"`   // 是否是框架菜单，可选字段
	IsCache   int64  `json:"isCache,optional"`   // 是否缓存，可选字段
	MenuType  string `json:"menuType,optional"`  // 菜单类型，可选字段
	Perms     string `json:"perms,optional"`     // 菜单权限，可选字段
	Icon      string `json:"icon,optional"`      // 菜单图标，可选字段
	Remark    string `json:"remark,optional"`    // 菜单备注，可选字段
}

type Menu struct {
	MenuId    int64   `json:"menuId"`
	MenuName  string  `json:"menuName"`
	ParentId  int64   `json:"parentId"`
	Order     int64   `json:"order"`
	Path      string  `json:"path"`
	Component string  `json:"component"`
	Query     string  `json:"query"`
	IsFrame   int64   `json:"isFrame"`
	IsCache   int64   `json:"isCache"`
	MenuType  string  `json:"menuType"`
	Visible   int64   `json:"visible"`
	Status    int64   `json:"status"`
	Perms     string  `json:"perms"`
	Icon      string  `json:"icon"`
	CreatedId int64   `json:"createdId"`
	CreatedBy string  `json:"createdBy"`
	UpdatedId int64   `json:"updatedId"`
	UpdatedBy string  `json:"updatedBy"`
	Remark    string  `json:"remark"`
	Children  []*Menu `json:"children,omitempty"`
	Date
}

type IndexMenuResp struct {
}

type AllMenuResp struct {
	Rest
	Data []*Menu `json:"data"`
}

type ShowMenuReq struct {
}

type MenuResp struct {
}

type ShowDepartmentReq struct {
	Id int64 `path:"id,optional"`
}

type DepartmentReq struct {
	Id       int64  `path:"id,optional"`
	ParentId int64  `json:"parentId,optional"` // 父级部门ID
	Name     string `json:"name"`              // 部门名称
	Sort     int64  `json:"sort,optional"`     // 排序字段
	Leader   string `json:"leader,optional"`   // 部门负责人
	Phone    string `json:"phone,optional"`    // 联系电话
	Email    string `json:"email,optional"`    // 部门邮箱
	Status   *int64 `json:"status,optional"`   // 部门状态（如启用或禁用）
	Paginate
}

type Department struct {
	Id        int64  `json:"id"`                  // 部门ID
	ParentId  int64  `json:"parentId,omitempty"`  // 父级部门ID
	Ancestors string `json:"ancestors,omitempty"` // 上级部门的祖先ID路径（可以自动生成）
	Name      string `json:"name"`                // 部门名称
	Sort      int64  `json:"sort,omitempty"`      // 排序字段
	Leader    string `json:"leader,omitempty"`    // 部门负责人
	Phone     string `json:"phone,omitempty"`     // 联系电话
	Email     string `json:"email,omitempty"`     // 部门邮箱
	Status    int64  `json:"status"`              // 部门状态（如启用或禁用）
	CreateBy  int64  `json:"createBy,omitempty"`  // 创建者ID
	UpdateBy  int64  `json:"updateBy,omitempty"`  // 更新者ID
	DeletedAt int64  `json:"deletedAt,omitempty"` // 删除时间
	Date
	Children []*Department `json:"children,omitempty"` // 子部门
}

type DepartmentResp struct {
	Rest
	Data Department `json:"data"`
}

type PaginateDepartment struct {
	Paginate
	Data []Department `json:"data"`
}

type IndexDepartmentResp struct {
	Rest
	Data PaginateDepartment `json:"data"`
}

type AllDepartmentResp struct {
	Rest
	Data []*Department `json:"data"`
}
