// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type TokenData struct {
	AccessToken  string `json:"access_token"`
	ExpiresAt    int64  `json:"expires_at"`
	RefreshToken string `json:"refresh_token"`
	ReExpiresAt  int64  `json:"re_expires_at"`
}

type LoginResp struct {
	Rest
	Data TokenData `json:"data"`
}

type Rest struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type HelloData struct {
	Id int64 `json:"id"`
}

type HelloResp struct {
	Rest
	Data HelloData `json:"data"`
}

type ShowRoleReq struct {
	Id int64 `path:"id,optional"`
}

type RoleReq struct {
	Id          int64  `path:"id,optional"`
	ParentId    int64  `json:"parentId,optional"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Sort        int64  `json:"sort,optional"`
	Status      int64  `json:"status,optional"`
	Paginate
}

type Role struct {
	Id          int64  `json:"id"`
	ParentId    int64  `json:"parentId"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Level       string `json:"level"`
	Sort        int64  `json:"sort"`
	Status      int64  `json:"status"`
	Date
	Children []*Role `json:"children,omitempty"`
}

type RoleResp struct {
	Rest
	Data Role `json:"data"`
}

type PaginateRole struct {
	Paginate
	Data []Role `json:"data"`
}

type IndexRoleResp struct {
	Rest
	Data PaginateRole `json:"data"`
}

type AllRoleResp struct {
	Rest
	Data []*Role `json:"data"`
}

type Date struct {
	CreatedAt   int64  `json:"createAt,optional"`
	CreatedTime string `json:"createdTime,optional"`
	UpdatedAt   int64  `json:"updatedAt,optional"`
	UpdatedTime string `json:"updatedTime,optional"`
}

type Paginate struct {
	Current  int64 `form:"current,optional,default=1" json:"current,optional"`
	PageSize int64 `form:"pageSize,optional,default=10" json:"pageSize,optional"`
	Total    int64 `json:"total,optional"`
}
