// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type TokenData struct {
	AccessToken  string `json:"access_token"`
	ExpiresAt    int64  `json:"expires_at"`
	RefreshToken string `json:"refresh_token"`
	ReExpiresAt  int64  `json:"re_expires_at"`
}

type LoginResp struct {
	Rest
	Data TokenData `json:"data"`
}

type Rest struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type HelloData struct {
	Id int64 `json:"id"`
}

type HelloResp struct {
	Rest
	Data HelloData `json:"data"`
}

type RoleReq struct {
	ParentId    int    `json:"parentId,optional"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Sort        int    `json:"sort,optional"`
	Status      int    `json:"status,optional"`
}

type Role struct {
}

type RoleResp struct {
	Rest
	Data []Role `json:"data"`
}
