// Code generated by goctl. DO NOT EDIT.

package department

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDepartmentFieldNames          = builder.RawFieldNames(&SysDepartment{})
	sysDepartmentRows                = strings.Join(sysDepartmentFieldNames, ",")
	sysDepartmentRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDepartmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDepartmentRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDepartmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysDepartmentIdPrefix   = "cache:sysDepartment:id:"
	cacheSysDepartmentNamePrefix = "cache:sysDepartment:name:"
)

type (
	sysDepartmentModel interface {
		Insert(ctx context.Context, data *SysDepartment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysDepartment, error)
		FindOneByName(ctx context.Context, name string) (*SysDepartment, error)
		Update(ctx context.Context, data *SysDepartment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysDepartmentModel struct {
		sqlc.CachedConn
		table string
	}

	SysDepartment struct {
		Id        int64          `db:"id"`         // 部门id
		ParentId  int64          `db:"parentId"`   // 父部门id
		Ancestors string         `db:"ancestors"`  // 组级列表
		Name      string         `db:"name"`       // 部门名称
		Sort      int64          `db:"sort"`       // 显示顺序
		DataScope int64          `db:"data_scope"` // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
		Leader    sql.NullString `db:"leader"`     // 负责人
		Phone     sql.NullString `db:"phone"`      // 联系电话
		Email     sql.NullString `db:"email"`      // 邮箱
		Status    int64          `db:"status"`     // 0=>停用，1=>启用
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		UpdatedAt time.Time      `db:"updated_at"`
		CreateBy  int64          `db:"create_by"`  // 创建者
		UpdateBy  int64          `db:"update_by"`  // 更新者
		DeletedAt sql.NullTime   `db:"deleted_at"` // 删除时间
	}
)

func newSysDepartmentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysDepartmentModel {
	return &defaultSysDepartmentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_department`",
	}
}

func (m *defaultSysDepartmentModel) withSession(session sqlx.Session) *defaultSysDepartmentModel {
	return &defaultSysDepartmentModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`sys_department`",
	}
}

func (m *defaultSysDepartmentModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysDepartmentIdKey := fmt.Sprintf("%s%v", cacheSysDepartmentIdPrefix, id)
	sysDepartmentNameKey := fmt.Sprintf("%s%v", cacheSysDepartmentNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysDepartmentIdKey, sysDepartmentNameKey)
	return err
}

func (m *defaultSysDepartmentModel) FindOne(ctx context.Context, id int64) (*SysDepartment, error) {
	sysDepartmentIdKey := fmt.Sprintf("%s%v", cacheSysDepartmentIdPrefix, id)
	var resp SysDepartment
	err := m.QueryRowCtx(ctx, &resp, sysDepartmentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDepartmentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDepartmentModel) FindOneByName(ctx context.Context, name string) (*SysDepartment, error) {
	sysDepartmentNameKey := fmt.Sprintf("%s%v", cacheSysDepartmentNamePrefix, name)
	var resp SysDepartment
	err := m.QueryRowIndexCtx(ctx, &resp, sysDepartmentNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", sysDepartmentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDepartmentModel) Insert(ctx context.Context, data *SysDepartment) (sql.Result, error) {
	sysDepartmentIdKey := fmt.Sprintf("%s%v", cacheSysDepartmentIdPrefix, data.Id)
	sysDepartmentNameKey := fmt.Sprintf("%s%v", cacheSysDepartmentNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDepartmentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Ancestors, data.Name, data.Sort, data.DataScope, data.Leader, data.Phone, data.Email, data.Status, data.CreateBy, data.UpdateBy, data.DeletedAt)
	}, sysDepartmentIdKey, sysDepartmentNameKey)
	return ret, err
}

func (m *defaultSysDepartmentModel) Update(ctx context.Context, newData *SysDepartment) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysDepartmentIdKey := fmt.Sprintf("%s%v", cacheSysDepartmentIdPrefix, data.Id)
	sysDepartmentNameKey := fmt.Sprintf("%s%v", cacheSysDepartmentNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDepartmentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ParentId, newData.Ancestors, newData.Name, newData.Sort, newData.DataScope, newData.Leader, newData.Phone, newData.Email, newData.Status, newData.CreateBy, newData.UpdateBy, newData.DeletedAt, newData.Id)
	}, sysDepartmentIdKey, sysDepartmentNameKey)
	return err
}

func (m *defaultSysDepartmentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysDepartmentIdPrefix, primary)
}

func (m *defaultSysDepartmentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDepartmentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDepartmentModel) tableName() string {
	return m.table
}
