// Code generated by goctl. DO NOT EDIT.

package menu

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
	"zerocms/api/model"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysMenuFieldNames          = builder.RawFieldNames(&SysMenu{})
	sysMenuRows                = strings.Join(sysMenuFieldNames, ",")
	sysMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(sysMenuFieldNames, "`menu_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(sysMenuFieldNames, "`menu_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysMenuMenuIdPrefix = "cache:sysMenu:menuId:"
	cacheSysMenuPermsPrefix  = "cache:sysMenu:perms:"
)

type (
	sysMenuModel interface {
		Insert(ctx context.Context, data *SysMenu) (sql.Result, error)
		FindOne(ctx context.Context, menuId int64) (*SysMenu, error)
		FindOneByPerms(ctx context.Context, perms sql.NullString) (*SysMenu, error)
		Update(ctx context.Context, data *SysMenu) error
		Delete(ctx context.Context, menuId int64) error
	}

	defaultSysMenuModel struct {
		sqlc.CachedConn
		table string
	}

	SysMenu struct {
		MenuId    int64          `db:"menu_id"`
		MenuName  string         `db:"menu_name"`
		ParentId  int64          `db:"parent_id"`
		Order     int64          `db:"order"`
		Path      string         `db:"path"`
		Component sql.NullString `db:"component"`
		Query     sql.NullString `db:"query"`
		IsFrame   int64          `db:"is_frame"`
		IsCache   int64          `db:"is_cache"`
		MenuType  string         `db:"menu_type"`
		Visible   int64          `db:"visible"`
		Status    int64          `db:"status"`
		Perms     sql.NullString `db:"perms"`
		Icon      string         `db:"icon"`
		CreatedId sql.NullInt64  `db:"created_id"`
		CreatedBy string         `db:"created_by"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedId sql.NullInt64  `db:"updated_id"`
		UpdatedBy string         `db:"updated_by"`
		UpdatedAt time.Time      `db:"updated_at"`
		Remark    string         `db:"remark"`
		DeletedAt sql.NullTime   `db:"deleted_at"`
	}
)

func newSysMenuModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysMenuModel {
	return &defaultSysMenuModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_menu`",
	}
}

func (m *defaultSysMenuModel) withSession(session sqlx.Session) *defaultSysMenuModel {
	return &defaultSysMenuModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`sys_menu`",
	}
}

func (m *defaultSysMenuModel) Delete(ctx context.Context, menuId int64) error {
	data, err := m.FindOne(ctx, menuId)
	if err != nil {
		return err
	}

	sysMenuMenuIdKey := fmt.Sprintf("%s%v", cacheSysMenuMenuIdPrefix, menuId)
	sysMenuPermsKey := fmt.Sprintf("%s%v", cacheSysMenuPermsPrefix, data.Perms)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `menu_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, menuId)
	}, sysMenuMenuIdKey, sysMenuPermsKey)
	return err
}

func (m *defaultSysMenuModel) FindOne(ctx context.Context, menuId int64) (*SysMenu, error) {
	sysMenuMenuIdKey := fmt.Sprintf("%s%v", cacheSysMenuMenuIdPrefix, menuId)
	var resp SysMenu
	err := m.QueryRowCtx(ctx, &resp, sysMenuMenuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `menu_id` = ? limit 1", sysMenuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, menuId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuModel) FindOneByPerms(ctx context.Context, perms sql.NullString) (*SysMenu, error) {
	sysMenuPermsKey := fmt.Sprintf("%s%v", cacheSysMenuPermsPrefix, perms)
	var resp SysMenu
	err := m.QueryRowIndexCtx(ctx, &resp, sysMenuPermsKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `perms` = ? limit 1", sysMenuRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, perms); err != nil {
			return nil, err
		}
		return resp.MenuId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuModel) Insert(ctx context.Context, data *SysMenu) (sql.Result, error) {
	sysMenuMenuIdKey := fmt.Sprintf("%s%v", cacheSysMenuMenuIdPrefix, data.MenuId)
	sysMenuPermsKey := fmt.Sprintf("%s%v", cacheSysMenuPermsPrefix, data.Perms)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysMenuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MenuName, data.ParentId, data.Order, data.Path, data.Component, data.Query, data.IsFrame, data.IsCache, data.MenuType, data.Visible, data.Status, data.Perms, data.Icon, data.CreatedId, data.CreatedBy, data.UpdatedId, data.UpdatedBy, data.Remark, data.DeletedAt)
	}, sysMenuMenuIdKey, sysMenuPermsKey)
	return ret, err
}

func (m *defaultSysMenuModel) Update(ctx context.Context, newData *SysMenu) error {
	data, err := m.FindOne(ctx, newData.MenuId)
	if err != nil {
		return err
	}

	sysMenuMenuIdKey := fmt.Sprintf("%s%v", cacheSysMenuMenuIdPrefix, data.MenuId)
	sysMenuPermsKey := fmt.Sprintf("%s%v", cacheSysMenuPermsPrefix, data.Perms)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `menu_id` = ?", m.table, sysMenuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MenuName, newData.ParentId, newData.Order, newData.Path, newData.Component, newData.Query, newData.IsFrame, newData.IsCache, newData.MenuType, newData.Visible, newData.Status, newData.Perms, newData.Icon, newData.CreatedId, newData.CreatedBy, newData.UpdatedId, newData.UpdatedBy, newData.Remark, newData.DeletedAt, newData.MenuId)
	}, sysMenuMenuIdKey, sysMenuPermsKey)
	return err
}

func (m *defaultSysMenuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysMenuMenuIdPrefix, primary)
}

func (m *defaultSysMenuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `menu_id` = ? limit 1", sysMenuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysMenuModel) tableName() string {
	return m.table
}
