// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"zerocms/api/model"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserTokenFieldNames          = builder.RawFieldNames(&SysUserToken{})
	sysUserTokenRows                = strings.Join(sysUserTokenFieldNames, ",")
	sysUserTokenRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserTokenFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysUserTokenRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserTokenFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysUserTokenIdPrefix           = "cache:sysUserToken:id:"
	cacheSysUserTokenAccessTokenPrefix  = "cache:sysUserToken:accessToken:"
	cacheSysUserTokenRefreshTokenPrefix = "cache:sysUserToken:refreshToken:"
)

type (
	sysUserTokenModel interface {
		Insert(ctx context.Context, data *SysUserToken) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysUserToken, error)
		FindOneByAccessToken(ctx context.Context, accessToken string) (*SysUserToken, error)
		FindOneByRefreshToken(ctx context.Context, refreshToken string) (*SysUserToken, error)
		Update(ctx context.Context, data *SysUserToken) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysUserTokenModel struct {
		sqlc.CachedConn
		table string
	}

	SysUserToken struct {
		Id           int64        `db:"id"`
		UserId       int64        `db:"user_id"`
		AccessToken  string       `db:"access_token"`
		ExpiresAt    sql.NullTime `db:"expires_at"`
		RefreshToken string       `db:"refresh_token"`
		ReExpiresAt  sql.NullTime `db:"re_expires_at"`
	}
)

func newSysUserTokenModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysUserTokenModel {
	return &defaultSysUserTokenModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_user_token`",
	}
}

func (m *defaultSysUserTokenModel) withSession(session sqlx.Session) *defaultSysUserTokenModel {
	return &defaultSysUserTokenModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`sys_user_token`",
	}
}

func (m *defaultSysUserTokenModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysUserTokenAccessTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenAccessTokenPrefix, data.AccessToken)
	sysUserTokenIdKey := fmt.Sprintf("%s%v", cacheSysUserTokenIdPrefix, id)
	sysUserTokenRefreshTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenRefreshTokenPrefix, data.RefreshToken)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysUserTokenAccessTokenKey, sysUserTokenIdKey, sysUserTokenRefreshTokenKey)
	return err
}

func (m *defaultSysUserTokenModel) FindOne(ctx context.Context, id int64) (*SysUserToken, error) {
	sysUserTokenIdKey := fmt.Sprintf("%s%v", cacheSysUserTokenIdPrefix, id)
	var resp SysUserToken
	err := m.QueryRowCtx(ctx, &resp, sysUserTokenIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysUserTokenRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserTokenModel) FindOneByAccessToken(ctx context.Context, accessToken string) (*SysUserToken, error) {
	sysUserTokenAccessTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenAccessTokenPrefix, accessToken)
	var resp SysUserToken
	err := m.QueryRowIndexCtx(ctx, &resp, sysUserTokenAccessTokenKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `access_token` = ? limit 1", sysUserTokenRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, accessToken); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserTokenModel) FindOneByRefreshToken(ctx context.Context, refreshToken string) (*SysUserToken, error) {
	sysUserTokenRefreshTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenRefreshTokenPrefix, refreshToken)
	var resp SysUserToken
	err := m.QueryRowIndexCtx(ctx, &resp, sysUserTokenRefreshTokenKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `refresh_token` = ? limit 1", sysUserTokenRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, refreshToken); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserTokenModel) Insert(ctx context.Context, data *SysUserToken) (sql.Result, error) {
	sysUserTokenAccessTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenAccessTokenPrefix, data.AccessToken)
	sysUserTokenIdKey := fmt.Sprintf("%s%v", cacheSysUserTokenIdPrefix, data.Id)
	sysUserTokenRefreshTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenRefreshTokenPrefix, data.RefreshToken)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sysUserTokenRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.AccessToken, data.ExpiresAt, data.RefreshToken, data.ReExpiresAt)
	}, sysUserTokenAccessTokenKey, sysUserTokenIdKey, sysUserTokenRefreshTokenKey)
	return ret, err
}

func (m *defaultSysUserTokenModel) Update(ctx context.Context, newData *SysUserToken) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysUserTokenAccessTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenAccessTokenPrefix, data.AccessToken)
	sysUserTokenIdKey := fmt.Sprintf("%s%v", cacheSysUserTokenIdPrefix, data.Id)
	sysUserTokenRefreshTokenKey := fmt.Sprintf("%s%v", cacheSysUserTokenRefreshTokenPrefix, data.RefreshToken)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysUserTokenRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.AccessToken, newData.ExpiresAt, newData.RefreshToken, newData.ReExpiresAt, newData.Id)
	}, sysUserTokenAccessTokenKey, sysUserTokenIdKey, sysUserTokenRefreshTokenKey)
	return err
}

func (m *defaultSysUserTokenModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysUserTokenIdPrefix, primary)
}

func (m *defaultSysUserTokenModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysUserTokenRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysUserTokenModel) tableName() string {
	return m.table
}
